package ru.realalerting.controlplane.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ClientAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientAllPropertiesEquals(Client expected, Client actual) {
        assertClientAutoGeneratedPropertiesEquals(expected, actual);
        assertClientAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientAllUpdatablePropertiesEquals(Client expected, Client actual) {
        assertClientUpdatableFieldsEquals(expected, actual);
        assertClientUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientAutoGeneratedPropertiesEquals(Client expected, Client actual) {
        assertThat(expected)
            .as("Verify Client auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientUpdatableFieldsEquals(Client expected, Client actual) {
        assertThat(expected)
            .as("Verify Client relevant properties")
            .satisfies(e -> assertThat(e.getProtocolAddress()).as("check protocolAddress").isEqualTo(actual.getProtocolAddress()))
            .satisfies(e -> assertThat(e.getProtocolPort()).as("check protocolPort").isEqualTo(actual.getProtocolPort()))
            .satisfies(e -> assertThat(e.getProtocolUri()).as("check protocolUri").isEqualTo(actual.getProtocolUri()))
            .satisfies(e -> assertThat(e.getProtocolStreamId()).as("check protocolStreamId").isEqualTo(actual.getProtocolStreamId()))
            .satisfies(
                e -> assertThat(e.getMetricProducerAddress()).as("check metricProducerAddress").isEqualTo(actual.getMetricProducerAddress())
            )
            .satisfies(e -> assertThat(e.getMetricProducerPort()).as("check metricProducerPort").isEqualTo(actual.getMetricProducerPort()))
            .satisfies(e -> assertThat(e.getMetricProducerUri()).as("check metricProducerUri").isEqualTo(actual.getMetricProducerUri()))
            .satisfies(
                e ->
                    assertThat(e.getMetricProducerStreamId())
                        .as("check metricProducerStreamId")
                        .isEqualTo(actual.getMetricProducerStreamId())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientUpdatableRelationshipsEquals(Client expected, Client actual) {
        assertThat(expected)
            .as("Verify Client relationships")
            .satisfies(e -> assertThat(e.getTenant()).as("check tenant").isEqualTo(actual.getTenant()));
    }
}
