consumer:
  streams:
    - subscription-type: mdc
      publication-ip: localhost
      publication-port: 6002
      ip: localhost
      port: 6003
      stream-id: 4
  idle-strategy: SleepingIdleStrategy
  media-path: /dev/shm/aeron